# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [closed]
    branches:
      - beta

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly-2020-03-19

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build nearcore
    - name: Build nearcore
      run: make release

    # Copy binaries to server
    - name: Copy binaries to a server
      run: |
        echo "${{ secrets.SSH_PRIV_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 700 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa 
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
        scp -r -o StrictHostKeyChecking=no target/release/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/near/
        
    # Run nearup with binaries
    - name: Run nearup with binaries
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo ~/.nearup/nearup stop && sudo ~/.nearup/nearup betanet --nodocker --binary-path ~/near/release/' 
